/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payment;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import login.home;
/**
 *
 * @author just
 */
public class payment extends javax.swing.JFrame {
Connection con= null;
    Statement stmt =null;
    ResultSet rs = null;
    /**
     * Creates new form payment
     */
    public payment() {
        initComponents();
         con= db.dbnnection();
    }
     public void reset(){
        ID.setText("");
        empid.setText("");
        empname.setText("");       
        salary.setText("");
        salarytype.setText(""); 
        dates.setText("");
        IDSERCH.setText("");
        phone.setText("");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        IDSERCH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        empname = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        salarytype = new javax.swing.JTextField();
        dates = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 250, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Phone");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 90, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Payment Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 140, 40));

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 140, 40));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, 140, 40));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 140, 40));

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 140, 40));

        jToggleButton1.setText("SEARCH");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 90, 30));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, 140, 40));
        getContentPane().add(IDSERCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 210, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("payment ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, -1));
        getContentPane().add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 250, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Employee ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, -1));

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setOpaque(true);
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 250, 30));
        getContentPane().add(empname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 250, 30));
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 250, 30));
        getContentPane().add(salarytype, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 250, 30));
        getContentPane().add(dates, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 250, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Employee salary Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Employee salary Amount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Employee name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        home sda = new home();
        sda.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{

        
           stmt = con.createStatement();
            String empids=empid.getText();
            String emname =empname.getText();
            String salarta =salary.getText();
            String salaryty =salarytype.getText();
            String date = dates.getText();
             String ephone = phone.getText();

            int EID= Integer.parseInt(ID.getText());
            String query = " UPDATE ancel_employee.payment SET EMP_ID=?,EMP_name=?,salary_amount=?,salary_type=?,date=?,phone=? WHERE payment_id=? ";

            PreparedStatement preparedStmt =con.prepareStatement(query);

            preparedStmt.setString(1,empids);
            preparedStmt.setString(2,emname);
            preparedStmt.setString(3,salarta);
            preparedStmt.setString(4,salaryty);
            preparedStmt.setString(5,date);
            preparedStmt.setString(6,ephone);

            preparedStmt.setInt(7,EID);
            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Update !");
            reset();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            stmt = con.createStatement();

            int EID= Integer.parseInt(ID.getText());

            String query="DELETE FROM ancel_employee.payment WHERE payment_id='"+EID+"'";

            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Successfully Delete !");
            reset();

        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{

            stmt = con.createStatement();
            String empids=empid.getText();
            String emname =empname.getText();
            String salarta =salary.getText();
            String salaryty =salarytype.getText();
            String date = dates.getText();
             String ephone = phone.getText();
             
              
            
            if(!empids.isEmpty()){
            if(!emname.isEmpty()){
                if(!salarta.isEmpty()){
                    if(!salaryty.isEmpty()){
                        if(!date.isEmpty()){
                            if(!ephone.isEmpty()){

            String query = "INSERT INTO ancel_employee.payment(payment_id,EMP_ID,EMP_name,salary_amount,salary_type,date,phone) VALUES (0,?,?,?,?,?,?)";

            PreparedStatement preparedStmt =con.prepareStatement(query);

            preparedStmt.setString(1,empids);
            preparedStmt.setString(2,emname);
            preparedStmt.setString(3,salarta);
            preparedStmt.setString(4,salaryty);
            preparedStmt.setString(5,date);
            preparedStmt.setString(6,ephone);
            preparedStmt.execute();
            JOptionPane.showMessageDialog(null,"Successfully Inserted !");
            reset();
                                             }else{
                                       JOptionPane.showMessageDialog(null, "PLEASE ENTER  Phone", "Phone  ", JOptionPane.ERROR_MESSAGE);
                                 }
                                 }else{
                                   JOptionPane.showMessageDialog(null, "PLEASE ENTER   Date  ", "  Date", JOptionPane.ERROR_MESSAGE);
                            }
                                       
                            }else{
                                JOptionPane.showMessageDialog(null, "PLEASE ENTER  Employee salary Type", "salary Type", JOptionPane.ERROR_MESSAGE);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "PLEASE ENTER Employee salary Amount ", "Amount", JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "PLEASE ENTER  employee name", "name", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "PLEASE ENTER employee id", "id", JOptionPane.ERROR_MESSAGE);
                }
            

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        try {
            stmt=con.createStatement();
            int EIDS= Integer.parseInt(IDSERCH.getText());

            

            String query2 = "SELECT * FROM ancel_employee.payment";
            rs=stmt.executeQuery(query2);

            while(rs.next()){
                if(EIDS==rs.getInt("payment_id")){
                    

                    ID.setText( rs.getString("payment_id"));
                    empid.setText( rs.getString("EMP_ID"));
                    empname.setText(rs.getString("EMP_name"));
                    salary.setText( rs.getString("salary_amount"));
                    salarytype.setText( rs.getString("salary_type"));
                    dates.setText(rs.getString("date"));
                     phone.setText(rs.getString("phone"));

                }

            }

        } catch (SQLException ex) {
            //Logger.getLogger(SearchAndEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDSERCH;
    private javax.swing.JTextField dates;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField empname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField salarytype;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
