/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leave;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import login.home;

/**
 *
 * @author just
 */
public class LEAVE_Emplooye extends javax.swing.JFrame {
 
    Connection con= null;
    Statement stmt =null;
    ResultSet rs = null;
    
    
    public LEAVE_Emplooye() {
        initComponents();
        con= dbcon.dbnnection();
    }

      public void reset(){
      ID.setText("");
      empid.setText("");
      levet.setText("");       
      date.setText("");
      returndate.setText("");
      position.setText("");
      IDSERCH.setText("");       
      name1.setText("");
      email1.setText("");
      phone1.setText("");
      
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IDSERCH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        levet = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        returndate = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 140, 40));

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 140, 40));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, 140, 40));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 140, 40));

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 140, 40));

        jToggleButton1.setText("SEARCH");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 90, 30));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, 140, 40));

        name1.setBackground(new java.awt.Color(204, 204, 204));
        name1.setOpaque(true);
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 250, 30));

        email1.setBackground(new java.awt.Color(204, 204, 204));
        email1.setOpaque(true);
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 250, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 90, -1));
        getContentPane().add(IDSERCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 210, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Phone");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 70, -1));

        phone1.setBackground(new java.awt.Color(204, 204, 204));
        phone1.setOpaque(true);
        getContentPane().add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 250, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Email");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 70, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("LEAVE Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Leave ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, -1));
        getContentPane().add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 250, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Employee ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 90, -1));

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setOpaque(true);
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 250, 30));
        getContentPane().add(levet, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 250, 30));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 250, 30));
        getContentPane().add(returndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 250, 30));
        getContentPane().add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 250, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("position");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Returnto work date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date requested");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Leave type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{

            stmt = con.createStatement();
            String empids=empid.getText();
            String leave =levet.getText();
            String datee =date.getText();
            String datere =returndate.getText();
            String posi = position.getText();
            
            if(!empids.isEmpty()){
            if(!leave.isEmpty()){
                if(!datee.isEmpty()){
                    if(!datere.isEmpty()){
                        
                            if(!posi.isEmpty()){
            

            String query = "INSERT INTO ancel_employee.leaveemp(leave_id,leave_type,date_request,return_to_work_date,position,EMP_ID) VALUES (0,?,?,?,?,?)";

            PreparedStatement preparedStmt =con.prepareStatement(query);

            preparedStmt.setString(1,leave);
            preparedStmt.setString(2,datee);
            preparedStmt.setString(3,datere);
            preparedStmt.setString(4,posi);
            preparedStmt.setString(5,empids);
            
            preparedStmt.execute();
            JOptionPane.showMessageDialog(null,"Successfully Inserted !");
            reset();
                                                 }else{
                                                    JOptionPane.showMessageDialog(null, "PLEASE ENTER  position", "  position", JOptionPane.ERROR_MESSAGE);
                                                }
                                            }else{
                                                    JOptionPane.showMessageDialog(null, "PLEASE ENTER Returnto work date     ", "work  ", JOptionPane.ERROR_MESSAGE);
                                                }
                                       
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "PLEASE ENTER  Date requested", " requested", JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "PLEASE ENTER Leave type", "type", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "PLEASE ENTER Employee ID", "ID", JOptionPane.ERROR_MESSAGE);
                }
            

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{

            stmt = con.createStatement();

            String empids=empid.getText();
            String leave =levet.getText();
            String datee =date.getText();
            String datere =returndate.getText();
            String posi = position.getText();

            int EID= Integer.parseInt(ID.getText());
            String query = " UPDATE ancel_employee.leaveemp SET leave_type=?,date_request=?,return_to_work_date=?,position=?,EMP_ID=? WHERE leave_id=? ";

            PreparedStatement preparedStmt =con.prepareStatement(query);

           preparedStmt.setString(1,leave);
            preparedStmt.setString(2,datee);
            preparedStmt.setString(3,datere);
            preparedStmt.setString(4,posi);
            preparedStmt.setString(5,empids);

            preparedStmt.setInt(6,EID);
            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Update !");
            reset();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_updateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            stmt = con.createStatement();

            int EID= Integer.parseInt(ID.getText());

            String query="DELETE FROM ancel_employee.leaveemp WHERE leave_id='"+EID+"'";

            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Successfully Update !");
            reset();

        } catch (SQLException ex) {
          System.out.print(ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        try {
            stmt=con.createStatement();
             int EIDS= Integer.parseInt(IDSERCH.getText());

           int EID= Integer.parseInt(IDSERCH.getText());

            String query = "SELECT * FROM ancel_employee.employee";
            rs=stmt.executeQuery(query);

            while(rs.next()){
                if(EID==rs.getInt("EMP_ID")){

                    name1.setText( rs.getString("EMPName"));
                    email1.setText( rs.getString("email"));
                    phone1.setText(rs.getString("phone"));
                 

                }

            }
            
            
             String query2 = "SELECT * FROM ancel_employee.leaveemp";
            rs=stmt.executeQuery(query2);

            while(rs.next()){
                if(EIDS==rs.getInt("EMP_ID")){

                    ID.setText( rs.getString("leave_id"));
                    levet.setText( rs.getString("leave_type"));
                    date.setText(rs.getString("date_request"));
                    returndate.setText( rs.getString("return_to_work_date"));
                    position.setText( rs.getString("position"));
                    empid.setText(rs.getString("EMP_ID"));
                 

                }

            }

        } catch (SQLException ex) {
            //Logger.getLogger(SearchAndEdit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  home sda = new home();
                sda.setVisible(true);
                this.setVisible(false);      
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEAVE_Emplooye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEAVE_Emplooye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEAVE_Emplooye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEAVE_Emplooye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEAVE_Emplooye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDSERCH;
    private javax.swing.JTextField date;
    private javax.swing.JLabel email1;
    private javax.swing.JTextField empid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField levet;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel phone1;
    private javax.swing.JTextField position;
    private javax.swing.JTextField returndate;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
